In [39]:
import pandas as pd

In [44]:
df = pd.read_csv('competitive-data-science-predict-future-sales/sales_train.csv')
df.head()
test = pd.read_csv('competitive-data-science-predict-future-sales/test.csv')

In [3]:
columns = df.columns
for c in columns:
    print(df[c].unique())

['02.01.2013' '03.01.2013' '05.01.2013' ... '28.10.2015' '25.10.2015'
 '13.10.2015']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]
[59 25 24 23 19 22 18 21 28 27 29 26  4  6  2  3  7  0  1 16 15  8 10 14
 13 12 53 31 30 32 35 56 54 47 50 42 43 52 51 41 38 44 37 46 45  5 57 58
 55 17  9 49 39 40 48 34 33 20 11 36]
[22154  2552  2554 ...  7610  7635  7640]
[  999.     899.    1709.05 ... 12198.    4454.    4040.  ]
[ 1.000e+00 -1.000e+00  3.000e+00  2.000e+00  4.000e+00  5.000e+00
  1.300e+01  7.000e+00  6.000e+00  8.000e+00  1.000e+01  1.100e+01
  3.000e+01  2.200e+01  1.400e+01  1.500e+01  9.000e+00  1.200e+01
  1.700e+01  1.900e+01  2.000e+01 -5.000e+00 -6.000e+00 -3.000e+00
 -2.000e+00  1.600e+01  6.400e+01  1.800e+01  2.900e+01  2.600e+01
  3.900e+01  2.100e+01  2.700e+01  5.300e+01  2.500e+01  2.300e+01
  2.400e+01  4.000e+01  2.800e+01  3.100e+01  3.600e+01 -4.000e+00
  3.200e+01  3.500e+01  4.100e+01  8.800e+01  4.400e+01

In [4]:
df['date'] = pd.to_datetime(df['date'], format='%d.%m.%Y' )

In [6]:
df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

In [7]:
df.head()

date  date_block_num  shop_id  item_id  item_price  item_cnt_day  day  \
0 2013-01-02               0       59    22154      999.00           1.0    2   
1 2013-01-03               0       25     2552      899.00           1.0    3   
2 2013-01-05               0       25     2552      899.00          -1.0    5   
3 2013-01-06               0       25     2554     1709.05           1.0    6   
4 2013-01-15               0       25     2555     1099.00           1.0   15   

   month  year  
0      1  2013  
1      1  2013  
2      1  2013  
3      1  2013  
4      1  2013

In [8]:
df.drop(columns=['date'])

date_block_num  shop_id  item_id  item_price  item_cnt_day  day  \
0                     0       59    22154      999.00           1.0    2   
1                     0       25     2552      899.00           1.0    3   
2                     0       25     2552      899.00          -1.0    5   
3                     0       25     2554     1709.05           1.0    6   
4                     0       25     2555     1099.00           1.0   15   
...                 ...      ...      ...         ...           ...  ...   
2935844              33       25     7409      299.00           1.0   10   
2935845              33       25     7460      299.00           1.0    9   
2935846              33       25     7459      349.00           1.0   14   
2935847              33       25     7440      299.00           1.0   22   
2935848              33       25     7460      299.00           1.0    3   

         month  year  
0            1  2013  
1            1  2013  
2            1  2013  
3            1  2013  
4            1  2013  
...        ...   ...  
2935844     10  2015  
2935845     10  2015  
2935846     10  2015  
2935847     10  2015  
2935848     10  2015  

[2935849 rows x 8 columns]

In [11]:
from sklearn.linear_model import LinearRegression

In [13]:
columns = ['shop_id', 'item_id']
x = df[columns]
y = df.item_cnt_day

reg = LinearRegression().fit(x,y)

In [14]:
reg.score(x,y)

0.00030996952501038955

In [17]:
import numpy as np
reg.predict(np.array([[59,22154]]))

array([1.30189571])

In [20]:
x = np.array(x)

In [21]:
x

array([[   59, 22154],
       [   25,  2552],
       [   25,  2552],
       ...,
       [   25,  7459],
       [   25,  7440],
       [   25,  7460]])

In [22]:
y = np.array(y)
y

array([ 1.,  1., -1., ...,  1.,  1.,  1.])

In [45]:
out_df = test
out_df

ID  shop_id  item_id
0            0        5     5037
1            1        5     5320
2            2        5     5233
3            3        5     5232
4            4        5     5268
...        ...      ...      ...
214195  214195       45    18454
214196  214196       45    16188
214197  214197       45    15757
214198  214198       45    19648
214199  214199       45      969

[214200 rows x 3 columns]

In [46]:
x_test = test[['shop_id', 'item_id']].values
x_test

array([[    5,  5037],
       [    5,  5320],
       [    5,  5233],
       ...,
       [   45, 15757],
       [   45, 19648],
       [   45,   969]])

In [48]:
predictions = reg.predict(x_test)
predictions

array([1.23257084, 1.23454177, 1.23393587, ..., 1.27027749, 1.29737605,
       1.16728767])

In [57]:
out_df = out_df.drop(columns = ['shop_id', 'item_id'])
out_df

ID
0            0
1            1
2            2
3            3
4            4
...        ...
214195  214195
214196  214196
214197  214197
214198  214198
214199  214199

[214200 rows x 1 columns]

In [58]:
out_df['item_cnt_month'] = predictions
out_df

ID  item_cnt_month
0            0        1.232571
1            1        1.234542
2            2        1.233936
3            3        1.233929
4            4        1.234180
...        ...             ...
214195  214195        1.289061
214196  214196        1.273279
214197  214197        1.270277
214198  214198        1.297376
214199  214199        1.167288

[214200 rows x 2 columns]

In [60]:
out_df.to_csv('submission.csv', index=False)